datadump.location:
  author: <authos file location>
  works: <works file location>

spring:
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: create_if_not_exists
      request:
        timeout: 15s
      connection:
        connect-timeout: 15s
        init-query-timeout: 15s

datastax.astra:
  secure-connect-bundle: secure-connect-ibdb.zip

astra.db:
  id: <id>
  region: <region>
  keyspace: main
  application.token: <token>


